# docker-compose.yml - IVO V2 SIMPLIFICADO (Migração MCP→Service Completa)
# 🎯 MIGRAÇÃO CONCLUÍDA: 2 containers → 1 container
# ✅ MCP Server integrado como ImageAnalysisService
# ✅ Performance melhorada (sem HTTP entre containers)
# ✅ Deploy mais simples e manutenção mais fácil

services:
  ivo-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ivo-v2-unified
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      
      # ✅ MIGRAÇÃO CONCLUÍDA - Não precisa mais de MCP_SERVER_HOST
      # Análise de imagens agora é feita via ImageAnalysisService integrado
      - IMAGE_ANALYSIS_ENABLED=true
      - IMAGE_ANALYSIS_MODE=integrated_service
      
    volumes:
      # ✅ Volumes com user mapping para segurança
      - ./src:/app/src:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - uploads_data:/app/uploads
    user: "1001:1001"  # ✅ Executa com UID/GID específicos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ivo-network
    # ✅ Limites de recursos otimizados (agora que é um container só)
    deploy:
      resources:
        limits:
          memory: 1.5G  # Aumentado pois agora inclui análise de imagens
          cpus: '0.75'   # Mais CPU para processamento integrado
        reservations:
          memory: 768M   # Reserva maior para estabilidade
          cpus: '0.5'

  # 🗑️ MCP Server REMOVIDO - Funcionalidade migrada para ImageAnalysisService
  # Antes:
  # mcp-server:
  #   build: ...
  #   command: ["python", "src/mcp/image_analysis_server.py"]
  #   ...
  # 
  # Agora: Integrado como src/services/image_analysis_service.py

volumes:
  uploads_data:
    driver: local
    # ✅ Volume isolado e seguro

networks:
  ivo-network:
    driver: bridge
    # ✅ Rede simplificada (um container apenas)

# =============================================================================
# 📊 RESULTADOS DA MIGRAÇÃO MCP → SERVICE
# =============================================================================
#
# ✅ ANTES (Complexo):
#   - 2 containers (ivo-app + mcp-server)
#   - Comunicação HTTP entre containers
#   - Docker network mais complexo
#   - Deploy mais lento
#   - Debugging distribuído
#   - Logs em múltiplos containers
#
# ✅ DEPOIS (Simples):
#   - 1 container único (ivo-app)
#   - Comunicação direta LangChain 0.3
#   - Deploy mais rápido
#   - Debugging centralizado
#   - Logs unificados
#   - Performance melhorada
#
# 🚀 COMANDOS DE TESTE:
#   docker-compose down
#   docker-compose build --no-cache
#   docker-compose up
#   
#   # Testar análise de imagens integrada
#   curl -X POST http://localhost:8000/api/v2/units/{unit_id}/vocabulary \
#     -F "image_1=@test_image.jpg"
#
# 🔧 MONITORAMENTO:
#   docker-compose logs -f ivo-app | grep "ImageAnalysisService"
#   docker-compose exec ivo-app python -c "from src.services.image_analysis_service import ImageAnalysisService; print('✅ Service disponível')"
#
# =============================================================================