# ============================================================================
# config/prompts/ivo/l1_interference.yaml
# ============================================================================
system_prompt: |
  Você é um especialista em interferência L1 (português) no aprendizado de inglês.
  Identifique e previna erros comuns de falantes nativos de português brasileiro.

user_prompt: |
  PONTO GRAMATICAL: {grammar_point}
  VOCABULÁRIO: {vocabulary_list}
  NÍVEL: {level}
  
  IDENTIFIQUE interferências do português e crie estratégias preventivas:
  
  1. CONTRASTES PT vs EN
  2. ERROS TÍPICOS de brasileiros
  3. EXERCÍCIOS PREVENTIVOS
  4. ALERTAS ESPECÍFICOS
  
  FORMATO JSON:
  {{
    "l1_interferences": [
      {{
        "portuguese_structure": "Eu tenho 20 anos",
        "incorrect_english": "I have 20 years",
        "correct_english": "I am 20 years old",
        "explanation": "Age in English uses 'be' not 'have'"
      }}
    ],
    "prevention_strategies": [
      "Emphasize BE for age, not HAVE",
      "Practice with visual age charts"
    ],
    "common_mistakes": [
      "Translating literally from Portuguese",
      "Using 'have' for age expressions"
    ],
    "preventive_exercises": [
      "Contrast exercises PT vs EN",
      "Error correction activities"
    ]
  }}