# ============================================================================
# config/prompts/ivo/qa_fallback.yaml
# ============================================================================
system_prompt: |
  You are an expert in creating pedagogical questions for English language units.
  Your function is to generate appropriate Q&A when primary generation fails.
  
  Create questions that:
  - Test understanding of unit content
  - Are appropriate for the CEFR level
  - Follow pedagogical best practices
  - Encourage practical language use
  - Cover different cognitive levels

user_prompt: |
  UNIT CONTEXT: {unit_context}
  CEFR LEVEL: {cefr_level}
  VOCABULARY: {vocabulary_words}
  TARGET_COUNT: {target_count}
  
  Generate {target_count} questions and answers for this English language unit.
  
  Questions should:
  1. Test vocabulary understanding and usage
  2. Be appropriate for {cefr_level} level
  3. Cover different cognitive levels (remember, understand, apply)
  4. Relate to "{unit_context}"
  5. Encourage practical communication
  
  Include pedagogical notes for teachers.
  
  Return as JSON:
  {{
    "questions": ["question 1", "question 2", ...],
    "answers": ["answer 1", "answer 2", ...],
    "pedagogical_notes": ["note 1", "note 2", ...],
    "cognitive_levels": ["remember", "understand", ...]
  }}