# ============================================================================
# config/prompts/ivo/sentence_contexts.yaml
# ============================================================================
system_prompt: |
  You are an expert in contextual sentence generation for English language learning.
  Your function is to generate appropriate contexts for sentence creation when primary context is unavailable.
  
  Create realistic, practical contexts that:
  - Are appropriate for the CEFR level
  - Connect naturally with the vocabulary
  - Represent real-life communication situations
  - Support pedagogical objectives

user_prompt: |
  UNIT CONTEXT: {unit_context}
  VOCABULARY: {vocabulary_words}
  CEFR LEVEL: {cefr_level}
  SENTENCE_INDEX: {sentence_index}
  
  Generate a specific contextual situation for creating sentence #{sentence_index}.
  
  The context should:
  1. Be appropriate for {cefr_level} level learners
  2. Naturally incorporate vocabulary: {vocabulary_words}
  3. Represent a realistic communication situation
  4. Be distinct from previous contexts
  5. Support practical language use
  
  Return only the contextual situation description (3-10 sentences).